List

In [6]:
#how to create 2d list
l = [1, 2, [3, 4, 5]]
print(l[2][1])

l2d = [[0,0,0] for i in range(10)]
l2d

l2d1 = [[j for j in range(3)] for i in range(6)]
l2d1

4


[[0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2]]

In [1]:
#input in 2d list
#if input format is as given below
#1 2 3
#4 5 6
row = 2
col = 3
lis2d = [[int(j) for j in input().strip().split(" ")] for i in range(row)]
lis2d

1 2 3
4 5 6


[[1, 2, 3], [4, 5, 6]]

In [8]:
#input in 2d list for below input format
#1 2 3 4 5 6
row = 2
col = 3
ip = input().strip().split(" ")
lis2d = [[int(ip[col*i + j]) for j in range(col)] for i in range(row)]
lis2d

1 2 3 4 5 6


[[1, 2, 3], [4, 5, 6]]

In [9]:
#Program of Wave Print

In [21]:
pt = input().strip().split(" ")

row = int(pt[0])
col = int(pt[1])

str = input().strip().split(" ")
array = [[int(str[col*i + j]) for j in range(col)] for i in range(row)]

max_name = "row"
max_sum = 0
no_of = 0
for i in range(row):
  cur_sum = sum(array[i])
  if cur_sum > max_sum:
    max_sum = cur_sum
    no_of = i

for i in range(col):
  cur_sum = 0
  for j in range(row):
    cur_sum += array[j][i]
  if cur_sum > max_sum:
    max_sum = cur_sum
    no_of = i
    max_name = "column"
    
print(max_name, no_of, max_sum)

3 3
3 6 9 1 4 7 2 8 9
column 2 25


In [31]:
#spiral print
str = input().strip().split(" ")

row = int(str[0])
col = int(str[1])

array =[[int(str[i * row + j + 2]) for j in range(col)] for i in range(row)]
print(array)
start_row = 0;
end_row = row - 1
start_col = 0
end_col = col - 1
print_count = 0
while print_count < len(str) - 2:
  for i in range(start_col, end_col + 1):
    print(array[start_row][i], end = " ")
    print_count += 1
    
  start_row += 1
  for i in range(start_row, end_row + 1):
    print(array[i][end_col], end = " ")
    print_count += 1
  end_col -= 1
  for i in range(end_col, start_col - 1, -1):
    print(array[end_row][i], end = " ")
    print_count += 1
  end_row -= 1
  for i in range(end_row, start_row - 1, -1):
    print(array[i][start_col], end = " ")
    print_count += 1
  start_col += 1

4 4 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
1 2 3 4 8 12 16 15 14 13 9 5 6 7 11 10 

IMPORTING

In [2]:
#importing some part from lib
#from x import y

#importing whole lib
#import x as y

import math
math.sqrt(10)

3.1622776601683795

In [10]:
import math as m
m.sqrt(10)

3.1622776601683795

In [11]:
from math import sqrt
sqrt(10)

3.1622776601683795

NUMPY

In [55]:
#how to create numpy array
import numpy as np
l = [1,2,3]
print(np.array(l))

#if any of element in list is a string the numpy array created will be of string type
l = [1, 2, "3"]
print(np.array(l)) 

#some methods
print(np.zeros(10))#default value is float
print(np.ones(10))#default is float

#to explicitly enter int value
print(np.zeros(10, int))
a = np.zeros(10)
print(type(a))
print(a.dtype)

a = np.zeros(10, int)
print(type(a))
print(a.dtype)

print(np.arange(10))



[1 2 3]
['1' '2' '3']
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0 0 0 0 0 0 0 0 0 0]
<class 'numpy.ndarray'>
float64
<class 'numpy.ndarray'>
int32
[0 1 2 3 4 5 6 7 8 9]


In [28]:
import numpy as np
#2d array
#enter tuple
print(np.zeros((2, 3), int))

#3d array
print(np.zeros((2,3,4), int))
#similaryl multidimensional arrays

[[0 0 0]
 [0 0 0]]
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [36]:
#auto conversion
l = [1, 2, 3]
#the numpy array generated will be of type int
a = np.array(l)
print(a)

#suppose we try to enter an int as string 
#it will be auto converted to int
a[0] = "5"# "5" is converted to 5
print(a)

#throws error
#a[0] = "5.0"

#throws error
#a[0] = "p"

#means once numpy array is created its datatype can't be changed

[1 2 3]
[5 2 3]


In [40]:
#slicing
print(a[0:1])

#shape(size of array)
print(a.shape)


[5]
(3,)


In [54]:
#accessing row and column in 2d array
p = np.array([[1,2,3,7,8],[4,5,6,9,10],[11,12,13,14,15]])
#accessing 0th row
print(p[0])

#accessing 0th column
print(p[:,0])
#p[:, 0] means i need everything in terms of row and need 0th col only in terms of col

print(p[0:2, 0])
print("to differentiate")
print(p[:, 2:4])

[1 2 3 7 8]
[ 1  4 11]
[1 4]
to differentiate
[[ 3  7]
 [ 6  9]
 [13 14]]


#NUMPY OPERATIONS

In [63]:
a = np.array([1,2,3])
b = np.array([4,5,6])

#add 2 to every element
print(a + 2)

#elementwise operation
print(a+b)
#if dimensions are different we get an error


print(a*2)

print(a*b) #elementwise

print(a**b)#elementwise


[3 4 5]
[5 7 9]
[2 4 6]
[ 4 10 18]
[  1  32 729]


In [66]:
#mean of an array
print(a.mean())
print(a.sum())

2.0
6


In [76]:
#sample problem to find square distance
import math
t = ((a-b) ** 2).sum()
print(t)
t = math.sqrt(t)
print(t)

27
5.196152422706632


In [80]:
# sample prob--->to calc sum((Xi- Xmean)^2)

x = np.array([1,3,5,6])
print(((x - x.mean()) * x).sum())

14.75


In [83]:
#dot product
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[10,20],[40,50],[70,80]])
a1.dot(a2)

array([[300, 360],
       [660, 810]])

In [91]:
#similary numpy is offering np.matrix() for matrix
#their operations also beahves like matrix operations
#like a*b will do matrix multiplication instead of individual element multiplication as in array

a = np.matrix('1 2 4; 3 4 5')
print(a)
a.shape

[[1 2 4]
 [3 4 5]]


(2, 3)

In [87]:
a = np.array([0, 1, 2, 3])
b = np.array([2, 3, 4, 5])
a.dot(b)

26

In [104]:
#output prob
print(np.sum([[0,2], [0,5]], axis = 1))#performs row-wise sum


print(np.sum([[0,2], [0,5]], axis = 0))#performs col-wise sum

[2 5]
[0 7]
