In [11]:
import numpy as np
from sklearn import preprocessing

In [12]:
X = np.array([[1.,-1.,2.], [2.,0.,0.],[0.,1.,-1.]])

In [13]:
x_scaled = preprocessing.scale(X)
print(x_scaled)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [14]:
print(x_scaled.mean(axis=0)) #to find mean (by default it is 0)
print(x_scaled.std(axis=0)) #to find std deviation (by default it is 1)

[0. 0. 0.]
[1. 1. 1.]


In [15]:
#in real application deployment we don't have testing data available with us to merge and scale accordingly
#so to overcome with this problems we just scale training data and store the parameters that were used for it's scaling
#then again use the same parameters for scaling the testing data
#e.g

scaler = preprocessing.StandardScaler() #similarly we have min-max scaler and other scalers
scaler.fit(X)
print(scaler.transform(X))
#we are getting exactly the same result as x_scaled

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [16]:
#now suppose we have a testing data
x_test = [[1,2,3]]
#and we want to scale this one accoding to previous parameters itself then
print(scaler.transform(x_test))

[[0.         2.44948974 2.13808994]]
